### ISSUE TITLE
cmake config error

### ISSUE THREAD

**Issue by shunguang** [kyu-sz/DeepMAR_deploy#3]
Hi Ken, 

Thanks for creating this repository, please add some pre-requirements to build your code. I have the following errors when doing the cmake config to build it on VS2015 in windows 7.

Thanks a lot!
-shunguang
====================
...
Detecting CXX compile features - done
CMake Error at src/CMakeLists.txt:11 (execute_process):
  execute_process given unknown argument "protoc".

CMake Error at src/CMakeLists.txt:18 (execute_process):
  execute_process given unknown argument "cp".

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CAFFE_LIB
    linked by target "DeepMARCaffe" in directory C:/Projects/2018/Object_Re_ID/src/DeepMAR_deploy/src

Configuring incomplete, errors occurred!
See also "C:/Projects/2018/Object_Re_ID/src/DeepMAR_deploy/vs2015_localBuild/CMakeFiles/CMakeOutput.log".
=============end===========

**Comment by kyu-sz** [comment]
Thank you for the information!
This module is only tested on Ubuntu. While it might be able to be modified to run on Windows, it may take huge effort.
I created this repository just for an example of deploying DeepMAR, so sorry but it is not intended to be made cross-platform. It would be highly appreciated if you could contribute some codes so that it can also be used on Windows!
